using System;
using System.Text;

namespace Rracf
{
    /// <summary>What goes into ACF_Slot&lt;slot&gt;.txt, beyond the camo grid.</summary>
    internal class SlotMeta
    {
        public string Name = "";
        public string PlainDesc = "";
        public string AbilityDescOrange = "";
        public string WarningDesc = "";
        public string SpecialDesc = "";
        public int BaseCamo;
        public TerrainGrid Grid = new TerrainGrid();
        public SlotAbilities Abilities = new SlotAbilities();
    }

    /// <summary>
    /// Generates the ACF_Slot&lt;slot&gt;.txt that ships beside the mod's .pak, in ACF 2.0's format.
    ///
    /// The layout follows ACF's own modder template, comments and all, because the file is meant to
    /// be opened in Notepad afterwards - the explanations are most of its value.
    ///
    /// ONE HARD RULE: never put a comment after a value on the same line. ACF only ignores lines
    /// that START with ; or #, so a trailing comment becomes part of the value - and since the
    /// ability flags scan for any digit 1-9, "INFAmmoFlag=0  ; set to 1" reads as ENABLED.
    /// </summary>
    internal static class SlotFile
    {
        public static string Generate(int slot, SlotMeta meta)
        {
            if (meta == null) meta = new SlotMeta();
            TerrainGrid grid = meta.Grid ?? new TerrainGrid();
            SlotAbilities ab = meta.Abilities ?? new SlotAbilities();

            int slotNumber = slot - 60; // slot 61 is "ACF Mod 1"
            string name = string.IsNullOrEmpty(meta.Name) ? "Rename me ACF Mod " + slotNumber : meta.Name;

            var sb = new StringBuilder();
            string bar = "; ==============================================================================";
            string rule = "; ------------------------------------------------------------------------------";

            sb.AppendLine(bar);
            sb.AppendLine(";  ACF slot metadata - SLOT " + slotNumber + "  (camo ID " + slot + ")");
            sb.AppendLine(bar);
            sb.AppendLine(";");
            sb.AppendLine(";  Put this file next to your .pak, inside your archive at:");
            sb.AppendLine(";      Content\\Paks\\mods\\");
            sb.AppendLine(";");
            sb.AppendLine(";  The filename must stay ACF_Slot" + slot + ".txt - that is how ACF knows which slot it");
            sb.AppendLine(";  describes. " + OtherSlots(slot));
            sb.AppendLine(";");
            sb.AppendLine(";  Lines starting with ; or # are ignored. Spaces around the = are fine.");
            sb.AppendLine(";  Delete any line you do not want and it falls back to the default.");
            sb.AppendLine(";");
            sb.AppendLine(";  To see exactly what ACF read from this file, use the console command:");
            sb.AppendLine(";      acfslots");
            sb.AppendLine(";");
            sb.AppendLine(";  It also names any line it could not parse. A typo reads as \"absent\", which");
            sb.AppendLine(";  otherwise looks identical to deliberately leaving something at 0 - so check");
            sb.AppendLine(";  acfslots after editing rather than assuming.");
            sb.AppendLine(";");
            if (slot == 65) AppendSlot65Caveats(sb);
            sb.AppendLine("; Built for V2.0+");
            sb.AppendLine(";  Generated by RRACF " + AppInfo.Version + ".");
            sb.AppendLine(rule);
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine("; --- Shown in the menus -------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("Name=" + name);
            AppendIfSet(sb, "PlainDesc", meta.PlainDesc);
            AppendIfSet(sb, "AbilityDescOrange", meta.AbilityDescOrange);
            AppendIfSet(sb, "WarningDesc", meta.WarningDesc);
            AppendIfSet(sb, "SpecialDesc", meta.SpecialDesc);
            sb.AppendLine();
            sb.AppendLine("; The description is cosmetic. Writing \"Never runs out of ammo\" here does not");
            sb.AppendLine("; grant it - the abilities further down are what actually do things.");
            sb.AppendLine();
            sb.AppendLine();
            AppendBaseCamoBlock(sb, meta.BaseCamo);
            AppendGridBlock(sb, grid, slot);
            AppendAbilitiesBlock(sb, ab);
            sb.AppendLine();
            sb.AppendLine("; --- Not supported yet --------------------------------------------------------");
            sb.AppendLine(";");
            sb.AppendLine("; ACF does not read these. Listed so the file format does not have to change when");
            sb.AppendLine("; they arrive; leaving them in causes no harm.");
            sb.AppendLine();
            sb.AppendLine("StandingMoveSpeedMultiplier=1");
            sb.AppendLine("CrouchMoveSpeedMultiplier=1");
            sb.AppendLine("CrawlMoveSpeedMultiplier=1");
            sb.AppendLine("HealthMultiplier=1");
            sb.AppendLine("LifeRecoveryMultiplier=1");
            return sb.ToString();
        }

        private static string OtherSlots(int slot)
        {
            var others = new System.Collections.Generic.List<string>();
            foreach (int s in Pipeline.ValidSlots)
            {
                if (s != slot) others.Add(s.ToString());
            }
            return "Use ACF_Slot" + string.Join("/", others.ToArray()) + ".txt for the other slots.";
        }

        /// <summary>Only ever written when the author actually filled the field in.</summary>
        private static void AppendIfSet(StringBuilder sb, string key, string value)
        {
            if (string.IsNullOrEmpty(value)) return;
            sb.AppendLine(key + "=" + value.Trim());
        }

        private static void AppendSlot65Caveats(StringBuilder sb)
        {
            sb.AppendLine(";  !! TWO DIFFERENCES ON THIS SLOT - READ BEFORE YOU BUILD AROUND IT !!");
            sb.AppendLine(";");
            sb.AppendLine(";  1. CONCEALMENT VALUES DO NOT WORK HERE. ACF reads BaseCamo and the per-terrain");
            sb.AppendLine(";     grid from this file correctly, and the game overrides them - slot 5");
            sb.AppendLine(";     conceals as Tiger Stripe whatever you write. Slots 1 to 4 are unaffected");
            sb.AppendLine(";     and honour both. If concealment matters to your mod, target slots 1 to 4.");
            sb.AppendLine(";");
            sb.AppendLine(";  2. NAME IS LIMITED TO 15 CHARACTERS. This slot borrows a menu row the game");
            sb.AppendLine(";     only ever labelled \"UNLOCKED\", and the buffer behind that word holds 15 and");
            sb.AppendLine(";     no more. A longer Name= is ignored rather than cut short, and the row falls");
            sb.AppendLine(";     back to \"ACF Mod 5\". Slots 1 to 4 have no such limit.");
            sb.AppendLine(";");
            sb.AppendLine(";  EVERYTHING ELSE WORKS exactly as on the other slots - description, colours,");
            sb.AppendLine(";  thumbnail, and every ability below.");
            sb.AppendLine(";");
        }

        private static void AppendBaseCamoBlock(StringBuilder sb, int baseCamo)
        {
            sb.AppendLine("; --- The simple option: one value, everywhere ---------------------------------");
            sb.AppendLine(";");
            sb.AppendLine("; BaseCamo applies whatever you are standing against. Positive hides you,");
            sb.AppendLine("; negative exposes you. 0 behaves like being Naked.");
            sb.AppendLine(";");
            sb.AppendLine("; This is NOT how the game itself works. No vanilla camo has a base value - all");
            sb.AppendLine("; of them sit at 0 here, and their whole strength comes from the per-terrain grid");
            sb.AppendLine("; further down. (Gold's -100 comes from game code, not this field. Black is the");
            sb.AppendLine("; single camo carrying a flat value, 25.)");
            sb.AppendLine(";");
            sb.AppendLine("; So: use BaseCamo if you just want \"hides a bit better than bare skin\" and would");
            sb.AppendLine("; rather not think about it. For a camo that feels like a real one, leave this at");
            sb.AppendLine("; 0 and fill in the grid instead.");
            sb.AppendLine(";");
            sb.AppendLine("; If you set both, they ADD - BaseCamo=30 with a grass value of 35 gives 65 in");
            sb.AppendLine("; grass, not 35.");
            sb.AppendLine(";");
            sb.AppendLine("; Stored as a signed byte, so -128 to 127. Stay within -100 to 100.");
            sb.AppendLine();
            sb.AppendLine("BaseCamo=" + baseCamo);
            sb.AppendLine();
            sb.AppendLine();
        }

        private static void AppendGridBlock(StringBuilder sb, TerrainGrid grid, int slot)
        {
            sb.AppendLine("; --- Per-terrain values: how vanilla camos really work ------------------------");
            sb.AppendLine(";");
            if (slot == 65)
            {
                sb.AppendLine("; NOTE FOR THIS SLOT: these are read correctly and then overridden by the game.");
                sb.AppendLine("; Slot 5 conceals as Tiger Stripe no matter what is written here. Kept so the");
                sb.AppendLine("; file is complete, and so it works if ACF fixes this later.");
                sb.AppendLine(";");
            }
            sb.AppendLine("; This is what makes a camo feel like a real one. A vanilla camo is not one");
            sb.AppendLine("; number - it has a value for every surface AND every stance. That is why Water");
            sb.AppendLine("; works underwater, Snow works against white, and going prone in grass helps.");
            sb.AppendLine(";");
            sb.AppendLine("; Each line takes FIVE numbers, in this order:");
            sb.AppendLine(";");
            sb.AppendLine(";       stand , crouch , prone , wall-stand , wall-crouch");
            sb.AppendLine(";");
            sb.AppendLine("; With BaseCamo left at 0, these numbers ARE the percentages the game shows, so");
            sb.AppendLine("; they line up directly with any vanilla camo's. A surface you leave out gets");
            sb.AppendLine("; BaseCamo, which at 0 means it conceals like bare skin.");
            sb.AppendLine(";");
            sb.AppendLine("; You may also write a single number - CamoGrass=35 - and ACF uses it for all");
            sb.AppendLine("; five. That is simpler, but going prone will then gain you nothing on that");
            sb.AppendLine("; surface, which is not how vanilla camos behave.");
            sb.AppendLine(";");
            sb.AppendLine("; Note it is not all positives. A good camo is BAD somewhere - that is what makes");
            sb.AppendLine("; picking one interesting, and it is worth deciding where yours should struggle.");
            sb.AppendLine(";");
            sb.AppendLine("; Surfaces are chosen by COLOR and MATERIAL, not by area. Standing by a tree you");
            sb.AppendLine("; may be on SoilBrown, then ObjBrown pressed against the trunk, then Grass a step");
            sb.AppendLine("; later.");
            sb.AppendLine();
            sb.AppendLine(";                 stand crouch prone  wall  wallcr");
            sb.AppendLine();
            sb.AppendLine("; Outdoors");
            AppendRows(sb, grid, Terrain.Outdoors);
            sb.AppendLine();
            sb.AppendLine("; Objects and props you stand on/against");
            AppendRows(sb, grid, Terrain.Objects);
            sb.AppendLine();
            sb.AppendLine("; Indoors - split by the color of the surface, not by the room");
            AppendRows(sb, grid, Terrain.Rooms);
            sb.AppendLine();
            sb.AppendLine();
        }

        private static void AppendAbilitiesBlock(StringBuilder sb, SlotAbilities ab)
        {
            sb.AppendLine("; --- Abilities - these work ---------------------------------------------------");
            sb.AppendLine(";");
            sb.AppendLine("; All off by default. Each mirrors something a vanilla camo already does.");
            sb.AppendLine(";");
            sb.AppendLine("; IMPORTANT: do not put a comment after a value on the same line. Only lines that");
            sb.AppendLine("; START with ; or # are ignored, so a trailing comment becomes part of the value.");
            sb.AppendLine();
            sb.AppendLine("; Infinite ammo. The two keys are INDEPENDENT - either one alone turns it on.");
            sb.AppendLine(";   INFAmmoFlag=1     every weapon costs no ammo    (like the Infinity Facepaint)");
            sb.AppendLine(";   INFAmmoWeapon=... only the weapons you list     (like Grenade Camo)");
            sb.AppendLine();
            sb.AppendLine("INFAmmoFlag=" + (ab.InfAmmoAll ? "1" : "0"));
            sb.AppendLine("INFAmmoWeapon=" + (ab.InfAmmoWeapons == null ? "" : ab.InfAmmoWeapons.Trim()));
            sb.AppendLine();
            sb.AppendLine("; Names for INFAmmoWeapon, separated by commas. Case does not matter, and spaces,");
            sb.AppendLine("; hyphens and underscores are ignored - \"AK-47\", \"ak 47\" and \"AK47\" are the same.");
            sb.AppendLine(";");
            sb.AppendLine(";   Handguns    MK22            M1911A1  (M1911, 1911)   Single Action Army (SAA)");
            sb.AppendLine(";   Shotguns    M37");
            sb.AppendLine(";   Snipers     SVD             Mosin Nagant (Mosin)");
            sb.AppendLine(";   SMGs        Scorpion");
            sb.AppendLine(";   Rifles      XM16E1 (M16)    AK-47 (AK, AK47)");
            sb.AppendLine(";   LMGs        M63");
            sb.AppendLine(";   Grenades    Grenade         WP Grenade (WP)          Stun Grenade (Stun)");
            sb.AppendLine(";               Smoke Grenade (Smoke)                    Chaff Grenade (Chaff)");
            sb.AppendLine(";   Misc        Cigarette Gas Spray (CGS, Gas, Cigarette)");
            sb.AppendLine(";               RPG-7 (RPG)     TNT      Claymore        Mousetraps");
            sb.AppendLine(";");
            sb.AppendLine("; A whole category can be named instead of listing its weapons:");
            sb.AppendLine(";");
            sb.AppendLine(";   Handguns  Shotguns  Snipers  SMGs  Rifles  LMGs  Grenades  Misc  Nonlethal");
            sb.AppendLine(";");
            sb.AppendLine("; Watch the S. \"Grenade\" is the frag grenade on its own; \"Grenades\" is the whole");
            sb.AppendLine("; category - frag, WP, stun, smoke and chaff. One letter, four extra weapons.");
            sb.AppendLine(";");
            sb.AppendLine("; Nonlethal = MK22, Mosin Nagant, Stun Grenade, Chaff Grenade, Cigarette Gas");
            sb.AppendLine("; Spray, Mousetraps.");
            sb.AppendLine(";");
            sb.AppendLine("; EZ Gun and the Patriot are deliberately absent - the game already gives those");
            sb.AppendLine("; infinite ammo. Melee and tools have no ammo to save.");
            sb.AppendLine();
            sb.AppendLine("; Steady aim - no shaking while aiming down the sights, the way Animals camo");
            sb.AppendLine("; does. First person only, which is true of Animals itself.");
            sb.AppendLine();
            sb.AppendLine("AnimalsSA=" + (ab.SteadyAim ? "1" : "0"));
            sb.AppendLine();
            sb.AppendLine("; Suppressor never wears out. A suppressor has a use count, not a percentage, and");
            sb.AppendLine("; loses one per shot. This only PREVENTS the count dropping - picking one up or");
            sb.AppendLine("; repairing it still works normally.");
            sb.AppendLine();
            sb.AppendLine("INFSuppressor=" + (ab.InfSuppressor ? "1" : "0"));
            sb.AppendLine();
            sb.AppendLine("; Footsteps make no noise. Real silence, not a volume reduction: the Sneaking");
            sb.AppendLine("; Suit, the White Tuxedo and Spirit share one check in the game and your slot is");
            sb.AppendLine("; added to it.");
            sb.AppendLine();
            sb.AppendLine("SilentSteps=" + (ab.SilentSteps ? "1" : "0"));
            sb.AppendLine();
        }

        /// <summary>Writes one key per surface, padded so the five columns line up in Notepad.</summary>
        private static void AppendRows(StringBuilder sb, TerrainGrid grid, string[] surfaces)
        {
            int width = 0;
            foreach (string s in Terrain.AllSurfaces())
            {
                if (s.Length + 1 > width) width = s.Length + 1;
            }

            foreach (string s in surfaces)
            {
                int[] r = grid.Row(s);
                string key = (s + "=").PadRight(width + 1);
                sb.AppendLine(key +
                    r[0].ToString().PadLeft(5) + "," +
                    r[1].ToString().PadLeft(5) + "," +
                    r[2].ToString().PadLeft(5) + "," +
                    r[3].ToString().PadLeft(6) + "," +
                    r[4].ToString().PadLeft(6));
            }
        }
    }
}
